# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Inicio
    url: '#home'
    weight: 20
  - name: Contenido
    url: '#contents'
    weight: 30
  - name: "Logística"
    url: '#logistics'
    weight: 40
  - name: Sesiones
    url: '#sesions'
    weight: 50
  - name: Profesor
    url: '#people'
    weight: 60
  - name: Material de apoyo
    url: courses/
    weight: 70
